name: Get & Cache Dependencies
description: Get npm dependencies and cache them
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        # ~/.cache/Cypress is needed for the Cypress binary
        path: |
          node_modules
          ~/.cache/Cypress
        key: npm-deps-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
