name: 'CI'
on:
  pull_request:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run tests
        run: npm run test:ci

  e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run e2e tests
        run: npm run e2e:ci
